// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/ClientData/ClientData.proto

package ClientData

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type ClientDataPutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClientDataPutReq) Reset() {
	*x = ClientDataPutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataPutReq) ProtoMessage() {}

func (x *ClientDataPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataPutReq.ProtoReflect.Descriptor instead.
func (*ClientDataPutReq) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDataPutReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientDataPutReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClientDataPutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientDataPutResp) Reset() {
	*x = ClientDataPutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataPutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataPutResp) ProtoMessage() {}

func (x *ClientDataPutResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataPutResp.ProtoReflect.Descriptor instead.
func (*ClientDataPutResp) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDataPutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the greetings
type ClientDataReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ClientDataReadReq) Reset() {
	*x = ClientDataReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataReadReq) ProtoMessage() {}

func (x *ClientDataReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataReadReq.ProtoReflect.Descriptor instead.
func (*ClientDataReadReq) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{2}
}

func (x *ClientDataReadReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientDataReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientDataReadResp) Reset() {
	*x = ClientDataReadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataReadResp) ProtoMessage() {}

func (x *ClientDataReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataReadResp.ProtoReflect.Descriptor instead.
func (*ClientDataReadResp) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDataReadResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClientDataReadResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientDataDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ClientDataDeleteReq) Reset() {
	*x = ClientDataDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataDeleteReq) ProtoMessage() {}

func (x *ClientDataDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataDeleteReq.ProtoReflect.Descriptor instead.
func (*ClientDataDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{4}
}

func (x *ClientDataDeleteReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientDataDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientDataDeleteResp) Reset() {
	*x = ClientDataDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientData_ClientData_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDataDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDataDeleteResp) ProtoMessage() {}

func (x *ClientDataDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientData_ClientData_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDataDeleteResp.ProtoReflect.Descriptor instead.
func (*ClientDataDeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_ClientData_ClientData_proto_rawDescGZIP(), []int{5}
}

func (x *ClientDataDeleteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ClientData_ClientData_proto protoreflect.FileDescriptor

var file_proto_ClientData_ClientData_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x3a, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x30, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x88, 0x02, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x75, 0x74, 0x12, 0x1c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x57, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ClientData_ClientData_proto_rawDescOnce sync.Once
	file_proto_ClientData_ClientData_proto_rawDescData = file_proto_ClientData_ClientData_proto_rawDesc
)

func file_proto_ClientData_ClientData_proto_rawDescGZIP() []byte {
	file_proto_ClientData_ClientData_proto_rawDescOnce.Do(func() {
		file_proto_ClientData_ClientData_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ClientData_ClientData_proto_rawDescData)
	})
	return file_proto_ClientData_ClientData_proto_rawDescData
}

var file_proto_ClientData_ClientData_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ClientData_ClientData_proto_goTypes = []interface{}{
	(*ClientDataPutReq)(nil),     // 0: ClientData.ClientDataPutReq
	(*ClientDataPutResp)(nil),    // 1: ClientData.ClientDataPutResp
	(*ClientDataReadReq)(nil),    // 2: ClientData.ClientDataReadReq
	(*ClientDataReadResp)(nil),   // 3: ClientData.ClientDataReadResp
	(*ClientDataDeleteReq)(nil),  // 4: ClientData.ClientDataDeleteReq
	(*ClientDataDeleteResp)(nil), // 5: ClientData.ClientDataDeleteResp
}
var file_proto_ClientData_ClientData_proto_depIdxs = []int32{
	0, // 0: ClientData.ClientData.ClientDataPut:input_type -> ClientData.ClientDataPutReq
	4, // 1: ClientData.ClientData.ClientDataDelete:input_type -> ClientData.ClientDataDeleteReq
	2, // 2: ClientData.ClientData.ClientDataRead:input_type -> ClientData.ClientDataReadReq
	1, // 3: ClientData.ClientData.ClientDataPut:output_type -> ClientData.ClientDataPutResp
	5, // 4: ClientData.ClientData.ClientDataDelete:output_type -> ClientData.ClientDataDeleteResp
	3, // 5: ClientData.ClientData.ClientDataRead:output_type -> ClientData.ClientDataReadResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ClientData_ClientData_proto_init() }
func file_proto_ClientData_ClientData_proto_init() {
	if File_proto_ClientData_ClientData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ClientData_ClientData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataPutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientData_ClientData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataPutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientData_ClientData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientData_ClientData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataReadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientData_ClientData_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientData_ClientData_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDataDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ClientData_ClientData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ClientData_ClientData_proto_goTypes,
		DependencyIndexes: file_proto_ClientData_ClientData_proto_depIdxs,
		MessageInfos:      file_proto_ClientData_ClientData_proto_msgTypes,
	}.Build()
	File_proto_ClientData_ClientData_proto = out.File
	file_proto_ClientData_ClientData_proto_rawDesc = nil
	file_proto_ClientData_ClientData_proto_goTypes = nil
	file_proto_ClientData_ClientData_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientDataClient is the client API for ClientData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientDataClient interface {
	// Sends a greeting
	ClientDataPut(ctx context.Context, in *ClientDataPutReq, opts ...grpc.CallOption) (*ClientDataPutResp, error)
	ClientDataDelete(ctx context.Context, in *ClientDataDeleteReq, opts ...grpc.CallOption) (*ClientDataDeleteResp, error)
	ClientDataRead(ctx context.Context, in *ClientDataReadReq, opts ...grpc.CallOption) (*ClientDataReadResp, error)
}

type clientDataClient struct {
	cc grpc.ClientConnInterface
}

func NewClientDataClient(cc grpc.ClientConnInterface) ClientDataClient {
	return &clientDataClient{cc}
}

func (c *clientDataClient) ClientDataPut(ctx context.Context, in *ClientDataPutReq, opts ...grpc.CallOption) (*ClientDataPutResp, error) {
	out := new(ClientDataPutResp)
	err := c.cc.Invoke(ctx, "/ClientData.ClientData/ClientDataPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientDataClient) ClientDataDelete(ctx context.Context, in *ClientDataDeleteReq, opts ...grpc.CallOption) (*ClientDataDeleteResp, error) {
	out := new(ClientDataDeleteResp)
	err := c.cc.Invoke(ctx, "/ClientData.ClientData/ClientDataDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientDataClient) ClientDataRead(ctx context.Context, in *ClientDataReadReq, opts ...grpc.CallOption) (*ClientDataReadResp, error) {
	out := new(ClientDataReadResp)
	err := c.cc.Invoke(ctx, "/ClientData.ClientData/ClientDataRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientDataServer is the server API for ClientData service.
type ClientDataServer interface {
	// Sends a greeting
	ClientDataPut(context.Context, *ClientDataPutReq) (*ClientDataPutResp, error)
	ClientDataDelete(context.Context, *ClientDataDeleteReq) (*ClientDataDeleteResp, error)
	ClientDataRead(context.Context, *ClientDataReadReq) (*ClientDataReadResp, error)
}

// UnimplementedClientDataServer can be embedded to have forward compatible implementations.
type UnimplementedClientDataServer struct {
}

func (*UnimplementedClientDataServer) ClientDataPut(context.Context, *ClientDataPutReq) (*ClientDataPutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientDataPut not implemented")
}
func (*UnimplementedClientDataServer) ClientDataDelete(context.Context, *ClientDataDeleteReq) (*ClientDataDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientDataDelete not implemented")
}
func (*UnimplementedClientDataServer) ClientDataRead(context.Context, *ClientDataReadReq) (*ClientDataReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientDataRead not implemented")
}

func RegisterClientDataServer(s *grpc.Server, srv ClientDataServer) {
	s.RegisterService(&_ClientData_serviceDesc, srv)
}

func _ClientData_ClientDataPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDataPutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDataServer).ClientDataPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientData.ClientData/ClientDataPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDataServer).ClientDataPut(ctx, req.(*ClientDataPutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientData_ClientDataDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDataDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDataServer).ClientDataDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientData.ClientData/ClientDataDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDataServer).ClientDataDelete(ctx, req.(*ClientDataDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientData_ClientDataRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDataReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDataServer).ClientDataRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientData.ClientData/ClientDataRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDataServer).ClientDataRead(ctx, req.(*ClientDataReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClientData.ClientData",
	HandlerType: (*ClientDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientDataPut",
			Handler:    _ClientData_ClientDataPut_Handler,
		},
		{
			MethodName: "ClientDataDelete",
			Handler:    _ClientData_ClientDataDelete_Handler,
		},
		{
			MethodName: "ClientDataRead",
			Handler:    _ClientData_ClientDataRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ClientData/ClientData.proto",
}
