// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/ClientMaster/ClientMaster.proto

package ClientMaster

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type ClientMasterFindDataNodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *ClientMasterFindDataNodeReq) Reset() {
	*x = ClientMasterFindDataNodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientMaster_ClientMaster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMasterFindDataNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMasterFindDataNodeReq) ProtoMessage() {}

func (x *ClientMasterFindDataNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientMaster_ClientMaster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMasterFindDataNodeReq.ProtoReflect.Descriptor instead.
func (*ClientMasterFindDataNodeReq) Descriptor() ([]byte, []int) {
	return file_proto_ClientMaster_ClientMaster_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMasterFindDataNodeReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// The response message containing the greetings
type ClientMasterFindDataNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port string `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *ClientMasterFindDataNodeResp) Reset() {
	*x = ClientMasterFindDataNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ClientMaster_ClientMaster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMasterFindDataNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMasterFindDataNodeResp) ProtoMessage() {}

func (x *ClientMasterFindDataNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ClientMaster_ClientMaster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMasterFindDataNodeResp.ProtoReflect.Descriptor instead.
func (*ClientMasterFindDataNodeResp) Descriptor() ([]byte, []int) {
	return file_proto_ClientMaster_ClientMaster_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMasterFindDataNodeResp) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_proto_ClientMaster_ClientMaster_proto protoreflect.FileDescriptor

var file_proto_ClientMaster_ClientMaster_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x1b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x32, 0x83, 0x01, 0x0a, 0x0c, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x73, 0x0a, 0x18, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ClientMaster_ClientMaster_proto_rawDescOnce sync.Once
	file_proto_ClientMaster_ClientMaster_proto_rawDescData = file_proto_ClientMaster_ClientMaster_proto_rawDesc
)

func file_proto_ClientMaster_ClientMaster_proto_rawDescGZIP() []byte {
	file_proto_ClientMaster_ClientMaster_proto_rawDescOnce.Do(func() {
		file_proto_ClientMaster_ClientMaster_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ClientMaster_ClientMaster_proto_rawDescData)
	})
	return file_proto_ClientMaster_ClientMaster_proto_rawDescData
}

var file_proto_ClientMaster_ClientMaster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ClientMaster_ClientMaster_proto_goTypes = []interface{}{
	(*ClientMasterFindDataNodeReq)(nil),  // 0: ClientMaster.ClientMasterFindDataNodeReq
	(*ClientMasterFindDataNodeResp)(nil), // 1: ClientMaster.ClientMasterFindDataNodeResp
}
var file_proto_ClientMaster_ClientMaster_proto_depIdxs = []int32{
	0, // 0: ClientMaster.ClientMaster.ClientMasterFindDataNode:input_type -> ClientMaster.ClientMasterFindDataNodeReq
	1, // 1: ClientMaster.ClientMaster.ClientMasterFindDataNode:output_type -> ClientMaster.ClientMasterFindDataNodeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ClientMaster_ClientMaster_proto_init() }
func file_proto_ClientMaster_ClientMaster_proto_init() {
	if File_proto_ClientMaster_ClientMaster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ClientMaster_ClientMaster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMasterFindDataNodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ClientMaster_ClientMaster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMasterFindDataNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ClientMaster_ClientMaster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ClientMaster_ClientMaster_proto_goTypes,
		DependencyIndexes: file_proto_ClientMaster_ClientMaster_proto_depIdxs,
		MessageInfos:      file_proto_ClientMaster_ClientMaster_proto_msgTypes,
	}.Build()
	File_proto_ClientMaster_ClientMaster_proto = out.File
	file_proto_ClientMaster_ClientMaster_proto_rawDesc = nil
	file_proto_ClientMaster_ClientMaster_proto_goTypes = nil
	file_proto_ClientMaster_ClientMaster_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientMasterClient is the client API for ClientMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientMasterClient interface {
	// Sends a greeting
	ClientMasterFindDataNode(ctx context.Context, in *ClientMasterFindDataNodeReq, opts ...grpc.CallOption) (*ClientMasterFindDataNodeResp, error)
}

type clientMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewClientMasterClient(cc grpc.ClientConnInterface) ClientMasterClient {
	return &clientMasterClient{cc}
}

func (c *clientMasterClient) ClientMasterFindDataNode(ctx context.Context, in *ClientMasterFindDataNodeReq, opts ...grpc.CallOption) (*ClientMasterFindDataNodeResp, error) {
	out := new(ClientMasterFindDataNodeResp)
	err := c.cc.Invoke(ctx, "/ClientMaster.ClientMaster/ClientMasterFindDataNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientMasterServer is the server API for ClientMaster service.
type ClientMasterServer interface {
	// Sends a greeting
	ClientMasterFindDataNode(context.Context, *ClientMasterFindDataNodeReq) (*ClientMasterFindDataNodeResp, error)
}

// UnimplementedClientMasterServer can be embedded to have forward compatible implementations.
type UnimplementedClientMasterServer struct {
}

func (*UnimplementedClientMasterServer) ClientMasterFindDataNode(context.Context, *ClientMasterFindDataNodeReq) (*ClientMasterFindDataNodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientMasterFindDataNode not implemented")
}

func RegisterClientMasterServer(s *grpc.Server, srv ClientMasterServer) {
	s.RegisterService(&_ClientMaster_serviceDesc, srv)
}

func _ClientMaster_ClientMasterFindDataNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMasterFindDataNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServer).ClientMasterFindDataNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientMaster.ClientMaster/ClientMasterFindDataNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServer).ClientMasterFindDataNode(ctx, req.(*ClientMasterFindDataNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClientMaster.ClientMaster",
	HandlerType: (*ClientMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientMasterFindDataNode",
			Handler:    _ClientMaster_ClientMasterFindDataNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ClientMaster/ClientMaster.proto",
}
