// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/DataMaster/DataMaster.proto

package DataMaster

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DataMasterReshardCompleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DataMasterReshardCompleteReq) Reset() {
	*x = DataMasterReshardCompleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_DataMaster_DataMaster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMasterReshardCompleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMasterReshardCompleteReq) ProtoMessage() {}

func (x *DataMasterReshardCompleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DataMaster_DataMaster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMasterReshardCompleteReq.ProtoReflect.Descriptor instead.
func (*DataMasterReshardCompleteReq) Descriptor() ([]byte, []int) {
	return file_proto_DataMaster_DataMaster_proto_rawDescGZIP(), []int{0}
}

func (x *DataMasterReshardCompleteReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DataMasterReshardCompleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DataMasterReshardCompleteResp) Reset() {
	*x = DataMasterReshardCompleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_DataMaster_DataMaster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMasterReshardCompleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMasterReshardCompleteResp) ProtoMessage() {}

func (x *DataMasterReshardCompleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DataMaster_DataMaster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMasterReshardCompleteResp.ProtoReflect.Descriptor instead.
func (*DataMasterReshardCompleteResp) Descriptor() ([]byte, []int) {
	return file_proto_DataMaster_DataMaster_proto_rawDescGZIP(), []int{1}
}

func (x *DataMasterReshardCompleteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_DataMaster_DataMaster_proto protoreflect.FileDescriptor

var file_proto_DataMaster_DataMaster_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22,
	0x38, 0x0a, 0x1c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x1d, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x80, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x72, 0x0a, 0x19, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x28, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_DataMaster_DataMaster_proto_rawDescOnce sync.Once
	file_proto_DataMaster_DataMaster_proto_rawDescData = file_proto_DataMaster_DataMaster_proto_rawDesc
)

func file_proto_DataMaster_DataMaster_proto_rawDescGZIP() []byte {
	file_proto_DataMaster_DataMaster_proto_rawDescOnce.Do(func() {
		file_proto_DataMaster_DataMaster_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_DataMaster_DataMaster_proto_rawDescData)
	})
	return file_proto_DataMaster_DataMaster_proto_rawDescData
}

var file_proto_DataMaster_DataMaster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_DataMaster_DataMaster_proto_goTypes = []interface{}{
	(*DataMasterReshardCompleteReq)(nil),  // 0: DataMaster.DataMasterReshardCompleteReq
	(*DataMasterReshardCompleteResp)(nil), // 1: DataMaster.DataMasterReshardCompleteResp
}
var file_proto_DataMaster_DataMaster_proto_depIdxs = []int32{
	0, // 0: DataMaster.DataMaster.DataMasterReshardComplete:input_type -> DataMaster.DataMasterReshardCompleteReq
	1, // 1: DataMaster.DataMaster.DataMasterReshardComplete:output_type -> DataMaster.DataMasterReshardCompleteResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_DataMaster_DataMaster_proto_init() }
func file_proto_DataMaster_DataMaster_proto_init() {
	if File_proto_DataMaster_DataMaster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_DataMaster_DataMaster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMasterReshardCompleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_DataMaster_DataMaster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMasterReshardCompleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_DataMaster_DataMaster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_DataMaster_DataMaster_proto_goTypes,
		DependencyIndexes: file_proto_DataMaster_DataMaster_proto_depIdxs,
		MessageInfos:      file_proto_DataMaster_DataMaster_proto_msgTypes,
	}.Build()
	File_proto_DataMaster_DataMaster_proto = out.File
	file_proto_DataMaster_DataMaster_proto_rawDesc = nil
	file_proto_DataMaster_DataMaster_proto_goTypes = nil
	file_proto_DataMaster_DataMaster_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataMasterClient is the client API for DataMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataMasterClient interface {
	DataMasterReshardComplete(ctx context.Context, in *DataMasterReshardCompleteReq, opts ...grpc.CallOption) (*DataMasterReshardCompleteResp, error)
}

type dataMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewDataMasterClient(cc grpc.ClientConnInterface) DataMasterClient {
	return &dataMasterClient{cc}
}

func (c *dataMasterClient) DataMasterReshardComplete(ctx context.Context, in *DataMasterReshardCompleteReq, opts ...grpc.CallOption) (*DataMasterReshardCompleteResp, error) {
	out := new(DataMasterReshardCompleteResp)
	err := c.cc.Invoke(ctx, "/DataMaster.DataMaster/DataMasterReshardComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataMasterServer is the server API for DataMaster service.
type DataMasterServer interface {
	DataMasterReshardComplete(context.Context, *DataMasterReshardCompleteReq) (*DataMasterReshardCompleteResp, error)
}

// UnimplementedDataMasterServer can be embedded to have forward compatible implementations.
type UnimplementedDataMasterServer struct {
}

func (*UnimplementedDataMasterServer) DataMasterReshardComplete(context.Context, *DataMasterReshardCompleteReq) (*DataMasterReshardCompleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataMasterReshardComplete not implemented")
}

func RegisterDataMasterServer(s *grpc.Server, srv DataMasterServer) {
	s.RegisterService(&_DataMaster_serviceDesc, srv)
}

func _DataMaster_DataMasterReshardComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataMasterReshardCompleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMasterServer).DataMasterReshardComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataMaster.DataMaster/DataMasterReshardComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMasterServer).DataMasterReshardComplete(ctx, req.(*DataMasterReshardCompleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataMaster.DataMaster",
	HandlerType: (*DataMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataMasterReshardComplete",
			Handler:    _DataMaster_DataMasterReshardComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/DataMaster/DataMaster.proto",
}
