// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/MasterData/MasterData.proto

package MasterData

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type MasterDataInformReshardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *MasterDataInformReshardReq) Reset() {
	*x = MasterDataInformReshardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterData_MasterData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterDataInformReshardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterDataInformReshardReq) ProtoMessage() {}

func (x *MasterDataInformReshardReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterData_MasterData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterDataInformReshardReq.ProtoReflect.Descriptor instead.
func (*MasterDataInformReshardReq) Descriptor() ([]byte, []int) {
	return file_proto_MasterData_MasterData_proto_rawDescGZIP(), []int{0}
}

func (x *MasterDataInformReshardReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the greetings
type MasterDataInformReshardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []byte `protobuf:"bytes,1,opt,name=Keys,proto3" json:"Keys,omitempty"`
}

func (x *MasterDataInformReshardResp) Reset() {
	*x = MasterDataInformReshardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterData_MasterData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterDataInformReshardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterDataInformReshardResp) ProtoMessage() {}

func (x *MasterDataInformReshardResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterData_MasterData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterDataInformReshardResp.ProtoReflect.Descriptor instead.
func (*MasterDataInformReshardResp) Descriptor() ([]byte, []int) {
	return file_proto_MasterData_MasterData_proto_rawDescGZIP(), []int{1}
}

func (x *MasterDataInformReshardResp) GetKeys() []byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MasterDataReshardDestinationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyDestination []byte `protobuf:"bytes,1,opt,name=KeyDestination,proto3" json:"KeyDestination,omitempty"`
}

func (x *MasterDataReshardDestinationReq) Reset() {
	*x = MasterDataReshardDestinationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterData_MasterData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterDataReshardDestinationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterDataReshardDestinationReq) ProtoMessage() {}

func (x *MasterDataReshardDestinationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterData_MasterData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterDataReshardDestinationReq.ProtoReflect.Descriptor instead.
func (*MasterDataReshardDestinationReq) Descriptor() ([]byte, []int) {
	return file_proto_MasterData_MasterData_proto_rawDescGZIP(), []int{2}
}

func (x *MasterDataReshardDestinationReq) GetKeyDestination() []byte {
	if x != nil {
		return x.KeyDestination
	}
	return nil
}

// The response message containing the greetings
type MasterDataReshardDestinationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *MasterDataReshardDestinationResp) Reset() {
	*x = MasterDataReshardDestinationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterData_MasterData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterDataReshardDestinationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterDataReshardDestinationResp) ProtoMessage() {}

func (x *MasterDataReshardDestinationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterData_MasterData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterDataReshardDestinationResp.ProtoReflect.Descriptor instead.
func (*MasterDataReshardDestinationResp) Descriptor() ([]byte, []int) {
	return file_proto_MasterData_MasterData_proto_rawDescGZIP(), []int{3}
}

func (x *MasterDataReshardDestinationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_MasterData_MasterData_proto protoreflect.FileDescriptor

var file_proto_MasterData_MasterData_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x2f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x36, 0x0a, 0x1a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x49, 0x0a, 0x1f, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a,
	0x0e, 0x4b, 0x65, 0x79, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x4b, 0x65, 0x79, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x20, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xf7, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x6c, 0x0a, 0x17, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x26, 0x2e,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x7b, 0x0a, 0x1c, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2b, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x64, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_MasterData_MasterData_proto_rawDescOnce sync.Once
	file_proto_MasterData_MasterData_proto_rawDescData = file_proto_MasterData_MasterData_proto_rawDesc
)

func file_proto_MasterData_MasterData_proto_rawDescGZIP() []byte {
	file_proto_MasterData_MasterData_proto_rawDescOnce.Do(func() {
		file_proto_MasterData_MasterData_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_MasterData_MasterData_proto_rawDescData)
	})
	return file_proto_MasterData_MasterData_proto_rawDescData
}

var file_proto_MasterData_MasterData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_MasterData_MasterData_proto_goTypes = []interface{}{
	(*MasterDataInformReshardReq)(nil),       // 0: MasterData.MasterDataInformReshardReq
	(*MasterDataInformReshardResp)(nil),      // 1: MasterData.MasterDataInformReshardResp
	(*MasterDataReshardDestinationReq)(nil),  // 2: MasterData.MasterDataReshardDestinationReq
	(*MasterDataReshardDestinationResp)(nil), // 3: MasterData.MasterDataReshardDestinationResp
}
var file_proto_MasterData_MasterData_proto_depIdxs = []int32{
	0, // 0: MasterData.MasterData.MasterDataInformReshard:input_type -> MasterData.MasterDataInformReshardReq
	2, // 1: MasterData.MasterData.MasterDataReshardDestination:input_type -> MasterData.MasterDataReshardDestinationReq
	1, // 2: MasterData.MasterData.MasterDataInformReshard:output_type -> MasterData.MasterDataInformReshardResp
	3, // 3: MasterData.MasterData.MasterDataReshardDestination:output_type -> MasterData.MasterDataReshardDestinationResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_MasterData_MasterData_proto_init() }
func file_proto_MasterData_MasterData_proto_init() {
	if File_proto_MasterData_MasterData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_MasterData_MasterData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterDataInformReshardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterData_MasterData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterDataInformReshardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterData_MasterData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterDataReshardDestinationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterData_MasterData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterDataReshardDestinationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_MasterData_MasterData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_MasterData_MasterData_proto_goTypes,
		DependencyIndexes: file_proto_MasterData_MasterData_proto_depIdxs,
		MessageInfos:      file_proto_MasterData_MasterData_proto_msgTypes,
	}.Build()
	File_proto_MasterData_MasterData_proto = out.File
	file_proto_MasterData_MasterData_proto_rawDesc = nil
	file_proto_MasterData_MasterData_proto_goTypes = nil
	file_proto_MasterData_MasterData_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MasterDataClient is the client API for MasterData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterDataClient interface {
	// Sends a greeting
	MasterDataInformReshard(ctx context.Context, in *MasterDataInformReshardReq, opts ...grpc.CallOption) (*MasterDataInformReshardResp, error)
	MasterDataReshardDestination(ctx context.Context, in *MasterDataReshardDestinationReq, opts ...grpc.CallOption) (*MasterDataReshardDestinationResp, error)
}

type masterDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterDataClient(cc grpc.ClientConnInterface) MasterDataClient {
	return &masterDataClient{cc}
}

func (c *masterDataClient) MasterDataInformReshard(ctx context.Context, in *MasterDataInformReshardReq, opts ...grpc.CallOption) (*MasterDataInformReshardResp, error) {
	out := new(MasterDataInformReshardResp)
	err := c.cc.Invoke(ctx, "/MasterData.MasterData/MasterDataInformReshard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataClient) MasterDataReshardDestination(ctx context.Context, in *MasterDataReshardDestinationReq, opts ...grpc.CallOption) (*MasterDataReshardDestinationResp, error) {
	out := new(MasterDataReshardDestinationResp)
	err := c.cc.Invoke(ctx, "/MasterData.MasterData/MasterDataReshardDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterDataServer is the server API for MasterData service.
type MasterDataServer interface {
	// Sends a greeting
	MasterDataInformReshard(context.Context, *MasterDataInformReshardReq) (*MasterDataInformReshardResp, error)
	MasterDataReshardDestination(context.Context, *MasterDataReshardDestinationReq) (*MasterDataReshardDestinationResp, error)
}

// UnimplementedMasterDataServer can be embedded to have forward compatible implementations.
type UnimplementedMasterDataServer struct {
}

func (*UnimplementedMasterDataServer) MasterDataInformReshard(context.Context, *MasterDataInformReshardReq) (*MasterDataInformReshardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasterDataInformReshard not implemented")
}
func (*UnimplementedMasterDataServer) MasterDataReshardDestination(context.Context, *MasterDataReshardDestinationReq) (*MasterDataReshardDestinationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasterDataReshardDestination not implemented")
}

func RegisterMasterDataServer(s *grpc.Server, srv MasterDataServer) {
	s.RegisterService(&_MasterData_serviceDesc, srv)
}

func _MasterData_MasterDataInformReshard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterDataInformReshardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).MasterDataInformReshard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterData.MasterData/MasterDataInformReshard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).MasterDataInformReshard(ctx, req.(*MasterDataInformReshardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterData_MasterDataReshardDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterDataReshardDestinationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).MasterDataReshardDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterData.MasterData/MasterDataReshardDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).MasterDataReshardDestination(ctx, req.(*MasterDataReshardDestinationReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MasterData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MasterData.MasterData",
	HandlerType: (*MasterDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MasterDataInformReshard",
			Handler:    _MasterData_MasterDataInformReshard_Handler,
		},
		{
			MethodName: "MasterDataReshardDestination",
			Handler:    _MasterData_MasterDataReshardDestination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/MasterData/MasterData.proto",
}
