// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/DataData/DataData.proto

package DataData

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DataDataMigrateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyValues []byte `protobuf:"bytes,1,opt,name=KeyValues,proto3" json:"KeyValues,omitempty"`
}

func (x *DataDataMigrateReq) Reset() {
	*x = DataDataMigrateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_DataData_DataData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDataMigrateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDataMigrateReq) ProtoMessage() {}

func (x *DataDataMigrateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DataData_DataData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDataMigrateReq.ProtoReflect.Descriptor instead.
func (*DataDataMigrateReq) Descriptor() ([]byte, []int) {
	return file_proto_DataData_DataData_proto_rawDescGZIP(), []int{0}
}

func (x *DataDataMigrateReq) GetKeyValues() []byte {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

type DataDataMigrateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DataDataMigrateResp) Reset() {
	*x = DataDataMigrateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_DataData_DataData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDataMigrateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDataMigrateResp) ProtoMessage() {}

func (x *DataDataMigrateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_DataData_DataData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDataMigrateResp.ProtoReflect.Descriptor instead.
func (*DataDataMigrateResp) Descriptor() ([]byte, []int) {
	return file_proto_DataData_DataData_proto_rawDescGZIP(), []int{1}
}

func (x *DataDataMigrateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_DataData_DataData_proto protoreflect.FileDescriptor

var file_proto_DataData_DataData_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x2f, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x12, 0x44, 0x61, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2f, 0x0a,
	0x13, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x5c,
	0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x50, 0x0a, 0x0f, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_DataData_DataData_proto_rawDescOnce sync.Once
	file_proto_DataData_DataData_proto_rawDescData = file_proto_DataData_DataData_proto_rawDesc
)

func file_proto_DataData_DataData_proto_rawDescGZIP() []byte {
	file_proto_DataData_DataData_proto_rawDescOnce.Do(func() {
		file_proto_DataData_DataData_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_DataData_DataData_proto_rawDescData)
	})
	return file_proto_DataData_DataData_proto_rawDescData
}

var file_proto_DataData_DataData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_DataData_DataData_proto_goTypes = []interface{}{
	(*DataDataMigrateReq)(nil),  // 0: DataData.DataDataMigrateReq
	(*DataDataMigrateResp)(nil), // 1: DataData.DataDataMigrateResp
}
var file_proto_DataData_DataData_proto_depIdxs = []int32{
	0, // 0: DataData.DataData.DataDataMigrate:input_type -> DataData.DataDataMigrateReq
	1, // 1: DataData.DataData.DataDataMigrate:output_type -> DataData.DataDataMigrateResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_DataData_DataData_proto_init() }
func file_proto_DataData_DataData_proto_init() {
	if File_proto_DataData_DataData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_DataData_DataData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDataMigrateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_DataData_DataData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDataMigrateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_DataData_DataData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_DataData_DataData_proto_goTypes,
		DependencyIndexes: file_proto_DataData_DataData_proto_depIdxs,
		MessageInfos:      file_proto_DataData_DataData_proto_msgTypes,
	}.Build()
	File_proto_DataData_DataData_proto = out.File
	file_proto_DataData_DataData_proto_rawDesc = nil
	file_proto_DataData_DataData_proto_goTypes = nil
	file_proto_DataData_DataData_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataDataClient is the client API for DataData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataDataClient interface {
	DataDataMigrate(ctx context.Context, in *DataDataMigrateReq, opts ...grpc.CallOption) (*DataDataMigrateResp, error)
}

type dataDataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataDataClient(cc grpc.ClientConnInterface) DataDataClient {
	return &dataDataClient{cc}
}

func (c *dataDataClient) DataDataMigrate(ctx context.Context, in *DataDataMigrateReq, opts ...grpc.CallOption) (*DataDataMigrateResp, error) {
	out := new(DataDataMigrateResp)
	err := c.cc.Invoke(ctx, "/DataData.DataData/DataDataMigrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataDataServer is the server API for DataData service.
type DataDataServer interface {
	DataDataMigrate(context.Context, *DataDataMigrateReq) (*DataDataMigrateResp, error)
}

// UnimplementedDataDataServer can be embedded to have forward compatible implementations.
type UnimplementedDataDataServer struct {
}

func (*UnimplementedDataDataServer) DataDataMigrate(context.Context, *DataDataMigrateReq) (*DataDataMigrateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataDataMigrate not implemented")
}

func RegisterDataDataServer(s *grpc.Server, srv DataDataServer) {
	s.RegisterService(&_DataData_serviceDesc, srv)
}

func _DataData_DataDataMigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDataMigrateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataDataServer).DataDataMigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataData.DataData/DataDataMigrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataDataServer).DataDataMigrate(ctx, req.(*DataDataMigrateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataData.DataData",
	HandlerType: (*DataDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataDataMigrate",
			Handler:    _DataData_DataDataMigrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/DataData/DataData.proto",
}
